defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/toot

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/toot
      - run: npm run lint:ci
      - store_test_results:
          path: reports

  jest:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/toot
      - run:
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest/results.xml"
      - store_test_results:
          path: reports

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/toot
      - run: npm run build
      - store_artifacts:
          path: ~/toot/build
      - persist_to_workspace:
          root: ~/toot
          paths:
            - build

  analyze:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/toot
      - run: npm run bundlesize
      - run: npm run analyze:ci
      - store_artifacts:
          path: ~/toot/analyze
          prefix: analyze

workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - jest:
          requires:
            - prepare
      - analyze:
          requires:
            - build
